name: mafuriko
description: "Mafuriko : Mapping Flooding Areas in Abidjan (MAFIA)."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  app_settings: ^5.1.1
  bloc: ^8.1.4
  dartz: ^0.10.1
  dio: ^5.5.0+1
  equatable: ^2.0.5
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flex_seed_scheme: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.1
  flutter_multi_formatter: ^2.12.8
  flutter_screenutil: ^5.9.3
  geolocator: ^12.0.0
  google_maps_flutter: ^2.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  pin_code_fields: ^8.0.1
  skeletonizer: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Monstserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900

        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900

        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700

        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700

        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 700

        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 700

        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400

        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
